//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nalai.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nalai.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string bt_add {
            get {
                return ResourceManager.GetString("bt.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string bt_cancel {
            get {
                return ResourceManager.GetString("bt.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string bt_close {
            get {
                return ResourceManager.GetString("bt.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string bt_edit {
            get {
                return ResourceManager.GetString("bt.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string bt_open {
            get {
                return ResourceManager.GetString("bt.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string bt_openFolder {
            get {
                return ResourceManager.GetString("bt.openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string bt_pause {
            get {
                return ResourceManager.GetString("bt.pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string bt_resume {
            get {
                return ResourceManager.GetString("bt.resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string coreRunningTime {
            get {
                return ResourceManager.GetString("coreRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string dc_downloadComplete {
            get {
                return ResourceManager.GetString("dc.downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string down_downloaded {
            get {
                return ResourceManager.GetString("down.downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string down_filename {
            get {
                return ResourceManager.GetString("down.filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string down_new {
            get {
                return ResourceManager.GetString("down.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string down_size {
            get {
                return ResourceManager.GetString("down.size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string down_speed {
            get {
                return ResourceManager.GetString("down.speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string down_status {
            get {
                return ResourceManager.GetString("down.status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string down_url {
            get {
                return ResourceManager.GetString("down.url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download list.
        /// </summary>
        internal static string downloadList {
            get {
                return ResourceManager.GetString("downloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk details.
        /// </summary>
        internal static string dp_chunkDetails {
            get {
                return ResourceManager.GetString("dp.chunkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string dp_downloading {
            get {
                return ResourceManager.GetString("dp.downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed.
        /// </summary>
        internal static string dp_maxSpeed {
            get {
                return ResourceManager.GetString("dp.maxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string dp_paused {
            get {
                return ResourceManager.GetString("dp.paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time.
        /// </summary>
        internal static string dp_remainingTime {
            get {
                return ResourceManager.GetString("dp.remainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string dp_size {
            get {
                return ResourceManager.GetString("dp.size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string dp_speed {
            get {
                return ResourceManager.GetString("dp.speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you delete or move it yet.
        /// </summary>
        internal static string msg_content_delOrMove {
            get {
                return ResourceManager.GetString("msg.content.delOrMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exist.
        /// </summary>
        internal static string msg_content_fileNotExist {
            get {
                return ResourceManager.GetString("msg.content.fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msg_title_error {
            get {
                return ResourceManager.GetString("msg.title.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalai.
        /// </summary>
        internal static string nalai_title {
            get {
                return ResourceManager.GetString("nalai.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save location.
        /// </summary>
        internal static string nt_savePath {
            get {
                return ResourceManager.GetString("nt.savePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        internal static string nt_title {
            get {
                return ResourceManager.GetString("nt.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Default Doanload Folder.
        /// </summary>
        internal static string nt_usingDefaultFolder {
            get {
                return ResourceManager.GetString("nt.usingDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Nalai.
        /// </summary>
        internal static string setting_about_nalai {
            get {
                return ResourceManager.GetString("setting.about.nalai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string setting_author {
            get {
                return ResourceManager.GetString("setting.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        internal static string setting_contributor {
            get {
                return ResourceManager.GetString("setting.contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        internal static string setting_contributors {
            get {
                return ResourceManager.GetString("setting.contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string setting_download {
            get {
                return ResourceManager.GetString("setting.download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string setting_general {
            get {
                return ResourceManager.GetString("setting.general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setting_language {
            get {
                return ResourceManager.GetString("setting.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string setting_languages {
            get {
                return ResourceManager.GetString("setting.languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string setting_license {
            get {
                return ResourceManager.GetString("setting.license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string setting_personalization {
            get {
                return ResourceManager.GetString("setting.personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string setting_theme {
            get {
                return ResourceManager.GetString("setting.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string setting_theme_dark {
            get {
                return ResourceManager.GetString("setting.theme.dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string setting_theme_light {
            get {
                return ResourceManager.GetString("setting.theme.light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string setting_title {
            get {
                return ResourceManager.GetString("setting.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string setting_version {
            get {
                return ResourceManager.GetString("setting.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating time.
        /// </summary>
        internal static string sort_by_creatingTime {
            get {
                return ResourceManager.GetString("sort.by.creatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string sort_by_name {
            get {
                return ResourceManager.GetString("sort.by.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string sort_by_size {
            get {
                return ResourceManager.GetString("sort.by.size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string sort_by_status {
            get {
                return ResourceManager.GetString("sort.by.status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string sort_descending {
            get {
                return ResourceManager.GetString("sort.descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core status.
        /// </summary>
        internal static string status_core {
            get {
                return ResourceManager.GetString("status.core", resourceCulture);
            }
        }
    }
}
