//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nalai.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nalai.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Button_Open {
            get {
                return ResourceManager.GetString("Button.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string Button_OpenFolder {
            get {
                return ResourceManager.GetString("Button.OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Button_Pause {
            get {
                return ResourceManager.GetString("Button.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDownload.
        /// </summary>
        internal static string Button_ReDownload {
            get {
                return ResourceManager.GetString("Button.ReDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Button_Resume {
            get {
                return ResourceManager.GetString("Button.Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dashboard_Cancel {
            get {
                return ResourceManager.GetString("Dashboard.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Dashboard_Desc {
            get {
                return ResourceManager.GetString("Dashboard.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Dashboard_Details {
            get {
                return ResourceManager.GetString("Dashboard.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Dashboard_Remove {
            get {
                return ResourceManager.GetString("Dashboard.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created time.
        /// </summary>
        internal static string Dashboard_SortByCreatedTime {
            get {
                return ResourceManager.GetString("Dashboard.SortByCreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dashboard_SortByName {
            get {
                return ResourceManager.GetString("Dashboard.SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Dashboard_SortBySize {
            get {
                return ResourceManager.GetString("Dashboard.SortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Dashboard_SortByStatus {
            get {
                return ResourceManager.GetString("Dashboard.SortByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Download_Downloaded {
            get {
                return ResourceManager.GetString("Download.Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string Download_FileName {
            get {
                return ResourceManager.GetString("Download.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Download_Id {
            get {
                return ResourceManager.GetString("Download.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Download_New {
            get {
                return ResourceManager.GetString("Download.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Download_Size {
            get {
                return ResourceManager.GetString("Download.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Download_Speed {
            get {
                return ResourceManager.GetString("Download.Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Download_Status {
            get {
                return ResourceManager.GetString("Download.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        internal static string Download_TotalSize {
            get {
                return ResourceManager.GetString("Download.TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Download_Url {
            get {
                return ResourceManager.GetString("Download.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string DownloadCompleteWindow_DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadCompleteWindow.DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk details.
        /// </summary>
        internal static string DownloadingWindow_ChunkDetails {
            get {
                return ResourceManager.GetString("DownloadingWindow.ChunkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created time.
        /// </summary>
        internal static string DownloadingWindow_CreatedTime {
            get {
                return ResourceManager.GetString("DownloadingWindow.CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string DownloadingWindow_Downloading {
            get {
                return ResourceManager.GetString("DownloadingWindow.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        internal static string DownloadingWindow_Eta {
            get {
                return ResourceManager.GetString("DownloadingWindow.Eta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed.
        /// </summary>
        internal static string DownloadingWindow_MaxSpeed {
            get {
                return ResourceManager.GetString("DownloadingWindow.MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string DownloadingWindow_Paused {
            get {
                return ResourceManager.GetString("DownloadingWindow.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string DownloadingWindow_Size {
            get {
                return ResourceManager.GetString("DownloadingWindow.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string DownloadingWindow_Speed {
            get {
                return ResourceManager.GetString("DownloadingWindow.Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string MainWindow_Downloads {
            get {
                return ResourceManager.GetString("MainWindow.Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string MainWindow_Running {
            get {
                return ResourceManager.GetString("MainWindow.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you delete or move it yet.
        /// </summary>
        internal static string Msg_DelOrMove {
            get {
                return ResourceManager.GetString("Msg.DelOrMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exist.
        /// </summary>
        internal static string Msg_FileNotExist {
            get {
                return ResourceManager.GetString("Msg.FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Msg_Title_Error {
            get {
                return ResourceManager.GetString("Msg.Title.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalai.
        /// </summary>
        internal static string Nalai_Title {
            get {
                return ResourceManager.GetString("Nalai.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save location.
        /// </summary>
        internal static string NewTaskWindow_SavePath {
            get {
                return ResourceManager.GetString("NewTaskWindow.SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        internal static string NewTaskWindow_Title {
            get {
                return ResourceManager.GetString("NewTaskWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Default Download Folder.
        /// </summary>
        internal static string NewTaskWindow_UsingDefaultFolder {
            get {
                return ResourceManager.GetString("NewTaskWindow.UsingDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Setting_Personalization {
            get {
                return ResourceManager.GetString("Setting.Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Nalai.
        /// </summary>
        internal static string Settings_AboutNalai {
            get {
                return ResourceManager.GetString("Settings.AboutNalai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Settings_Author {
            get {
                return ResourceManager.GetString("Settings.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        internal static string Settings_Contributor {
            get {
                return ResourceManager.GetString("Settings.Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        internal static string Settings_Contributors {
            get {
                return ResourceManager.GetString("Settings.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Settings_Download {
            get {
                return ResourceManager.GetString("Settings.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string Settings_License {
            get {
                return ResourceManager.GetString("Settings.License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        internal static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings.StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string Settings_StartWithWindows {
            get {
                return ResourceManager.GetString("Settings.StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core status.
        /// </summary>
        internal static string Status_Core {
            get {
                return ResourceManager.GetString("Status.Core", resourceCulture);
            }
        }
    }
}
