//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nalai.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nalai.Resources.Translation.ja", typeof(Translation_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 増加.
        /// </summary>
        internal static string bt_add {
            get {
                return ResourceManager.GetString("bt.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止.
        /// </summary>
        internal static string bt_cancel {
            get {
                return ResourceManager.GetString("bt.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string bt_close {
            get {
                return ResourceManager.GetString("bt.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エディット.
        /// </summary>
        internal static string bt_edit {
            get {
                return ResourceManager.GetString("bt.edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 見せる.
        /// </summary>
        internal static string bt_open {
            get {
                return ResourceManager.GetString("bt.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダを開く.
        /// </summary>
        internal static string bt_openFolder {
            get {
                return ResourceManager.GetString("bt.openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーズ.
        /// </summary>
        internal static string bt_pause {
            get {
                return ResourceManager.GetString("bt.pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジュメ.
        /// </summary>
        internal static string bt_resume {
            get {
                return ResourceManager.GetString("bt.resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働中のコア.
        /// </summary>
        internal static string coreRunningTime {
            get {
                return ResourceManager.GetString("coreRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string down_id {
            get {
                return ResourceManager.GetString("down.id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイズ.
        /// </summary>
        internal static string down_size {
            get {
                return ResourceManager.GetString("down.size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string down_url {
            get {
                return ResourceManager.GetString("down.url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        internal static string dp_eta {
            get {
                return ResourceManager.GetString("dp.eta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナライ.
        /// </summary>
        internal static string nalai_title {
            get {
                return ResourceManager.GetString("nalai.title", resourceCulture);
            }
        }
    }
}
